// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wqgzezghgwmdpamxptre.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndxZ3plemdoZ3dtZHBhbXhwdHJlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYwMzM5ODcsImV4cCI6MjA1MTYwOTk4N30.09NAjx0sFuAipyAiSwseLPa0aKMrIRSTEu7tCJ9Zuu0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);